# Deployment API 버전 : apps/v1
# Deployment 전략 : Recreate

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-deployment
spec:
  strategy:
  # 기존 pod 종료 후 새로운 pod 생성 
  # 기본 전략은 RollingUpdate
    type: Recreate 
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: yoonjeong/my-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
