# replicaSet API 버전 : apps/v1
# replicaSet 이름 : blue-replica-set
# replicaSet replicas : 3

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: blue-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels: # 레이블 선언 selector 와 일치
        app: blue-app
    spec:
      containers:
        - name: blue-app
          image: yoonjeong/blue-app:1.0
          ports:
            - containerPort: 8080
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

